[package]
name = "bombardier"
version = "0.1.0"
authors = ["Coding Yogi<aniket.g2185@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.48", features = ["derive"]}
serde_json = "1.0.48"
log = "0.4.8"
pretty_env_logger = "0.4"
clap = "2.33.0"
reqwest = { version = "0.10.4", features = ["json", "blocking", "cookies"] }
tokio = { version = "0.2", features = ["full"] }
rayon = "1.3.0"
prettytable-rs = "0.8"

rand = "0.7.3"