[package]
name = "bombardier"
version = "0.1.0"
authors = ["Coding Yogi<aniket.g2185@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.48", features = ["derive"]}
serde_json = "1.0.48"
log = "0.4.8"
pretty_env_logger = "0.4"
clap = "2.33.0"
base64 = "0.12.0"
rand = "0.7.3"
reqwest = { version = "0.10.4", features = ["json", "blocking"] }
tokio = { version = "0.2", features = ["full"] }
# awc = "2.0.0-alpha.1"
# actix-rt = "1.0.0"
async-std = "1.5.0"