[package]
name = "bombardier"
version = "0.1.0"
authors = ["Coding Yogi<aniket.g2185@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ajson = "0.2.3"
async-std = "1.5.0"
clap = "2.33.0"
chrono = "0.4"
csv = "1.1.3"
log = "0.4.8"
pretty_env_logger = "0.4"
prettytable-rs = "0.8"
rayon = "1.3.0"
regex = "1"
reqwest = { version = "0.10.4", features = ["json", "blocking", "cookies"] }
serde = { version = "1.0.48", features = ["derive"]}
serde_json = "1.0.48"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
tokio = { version = "0.2", features = ["full"] }
