[package]
name = "bombardier"
version = "0.1.0"
authors = ["Coding Yogi<aniket.g2185@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.48", features = ["derive"]}
serde_json = "1.0.48"
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.0"
base64 = "0.12.0"
