apiVersion: v1
kind: Service
metadata:
  name: bombardier-hub
  labels:
    name: bombardier-hub
spec:
  selector:
      app: bombardier-hub
  ports:
    - protocol: TCP
      port: 9000  
      name: rest
    - protocol: TCP
      port: 9001
      name: socket
  type: NodePort