name: bombardier

on:
  push:
    tags:
      - '*'
    paths-ignore: 
      - 'docs/**'
      - 'readme.md'
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:q
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --release
    - name: release
      uses: svenstaro/upload-release-action@v1-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./target/release/bombardier
        asset_name: bombardier-linux
        tag: ${{ github.ref }}

  MacOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: get libxml2, pkg-config 
      run: brew install pkg-config libxml2; export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
    - name: build
      run: cargo build --release
    - name: release
      uses: svenstaro/upload-release-action@v1-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./target/release/bombardier
        asset_name: bombardier-macos
        tag: ${{ github.ref }}