name: bombardier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Get Libxml2 macos
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config libxml2; export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
    - name: Get Libxml2 for windows
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-WebRequest -Uri https://www.zlatkovic.com/pub/libxml/64bit/libxml2-2.9.3-win32-x86_64.7z -OutFile C:\libxml2-2.9.3-win32-x86_64.7z
        & ${env:ProgramFiles}\7-Zip\7z.exe x C:\libxml2-2.9.3-win32-x86_64.7z -oC:\libxml2
        set PKG_CONFIG_PATH=C:\libxml2\lib\pkgconfig
    - name: Install pkgconfiglite
      if: matrix.os == 'windows-latest'
      run: choco install pkgconfiglite
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
