name: bombardier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Get Libxml2
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config libxml2; export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build For Windows
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; rustup target add x86_64-pc-windows-gnu
        sudo apt install mingw-w64; echo "completed installing mingw"
        cat >>~/.cargo/config <<EOF
        > [target.x86_64-pc-windows-gnu]
        > linker = "x86_64-w64-mingw32-gcc"
        > ar = "x86_64-w64-mingw32-gcc-ar"
        > EOF
        
        cargo build --release --target=x86_64-pc-windows-gnu --verbose
      
