name: bombardier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --verbose

  MacOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: get libxml2, pkg-config 
      run: brew install pkg-config libxml2; export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
    - name: build
      run: cargo build --verbose

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
    - uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-gnu
        toolchain: stable-x86_64-pc-windows-gnu
        default: true
        override: true
    - name: install mingw-w64-x86_64-toolchain & libxml2
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain libxml2-devel
    - name: build
      env:
        PKG_CONFIG_PATH: 'D:\a\_temp\msys\msys64\usr\lib\pkgconfig'
      run: |
        $env:path = "D:\a\_temp\msys\msys64\mingw64\bin;" + $env:path
        Add-Content ~/.cargo/config "[target.x86_64-pc-windows-gnu]`nlinker = `"D:\\a\\_temp\\msys\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe`"`nar = `"D:\\a\\_temp\\msys\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc-ar.exe`""
        cargo build --target=x86_64-pc-windows-gnu
