name: bombardier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
        
    - name: Install Msys2
      if: matrix.os == 'windows-latest'
      run: choco install msys2
        
    - name: Install pkgconfiglite
      if: matrix.os == 'windows-latest'
      run: choco install pkgconfiglite
    
    - name: Install libxml2 for windows
      if: matrix.os == 'windows-latest'
      run: pacman -S libxml2-devel
      
    - uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-gnu
        toolchain: stable
        default: true
      
    - name: Build for windows
      if: matrix.os == 'windows-latest'
      run: |
        $Env:PKG_CONFIG_PATH="C:\libxml2\lib\pkgconfig"
        Add-Content ~/.cargo/config "[target.x86_64-pc-windows-gnu]`nlinker = `"x86_64-w64-mingw32-gcc`"`nar = `"x86_64-w64-mingw32-gcc-ar`""
        cargo build --target=x86_64-pc-windows-gnu --verbose
        
      
