name: bombardier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Get Libxml2
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config libxml2; export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
    - name: Install pkgconfiglite
      if: matrix.os == 'windows-latest'
      run: choco install pkgconfiglite
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
