name: bombardier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
    - uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-gnu
        toolchain: stable
    
    - name: Install pkgconfig
      if: matrix.os == 'windows-latest'
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-pkg-config
    
    - name: Install libxml2 for windows
      if: matrix.os == 'windows-latest'
      run: msys2do pacman --noconfirm -S libxml2-devel
 
    - name: Build for windows
      if: matrix.os == 'windows-latest'
      env:
        PKG_CONFIG_PATH: 'D:\a\_temp\msys\msys64\usr\lib\pkgconfig'
      run: |
        $env:PKG_CONFIG_PATH 
        where.exe pkg-config
        Add-Content ~/.cargo/config "[target.x86_64-pc-windows-gnu]`nlinker = `"x86_64-w64-mingw32-gcc`"`nar = `"x86_64-w64-mingw32-gcc-ar`""
        cargo build --target=x86_64-pc-windows-gnu --verbose
        
      
